services:
    db:
        image: mariadb:11.4.2
        restart: unless-stopped
        container_name: "mariadb"
        environment:
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${DB_NAME}
            - MARIADB_USER=${DB_USER}
            - MARIADB_PASSWORD=${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        restart : unless-stopped
        container_name: "phpmyadmin"
        ports:
            - "${PHP_MY_ADMIN_PORT}:80"
        depends_on:
            - db
        environment:
            - PMA_HOST=${DB_HOST}
            - PMA_PORT=${DB_PORT}

    symfony:
        build:
            context: ./backend
            dockerfile: ./docker/Dockerfile.prod
        restart: unless-stopped
        container_name: "symfony"
        env_file:
            - .env.prod
        ports:
            - "${BACKEND_PORT}:80"
        depends_on:
            - db

    nuxt:
        build:
            context: ./frontend
            dockerfile: ./docker/Dockerfile.prod
        restart: unless-stopped
        container_name: "nuxt"
        ports:
            - "${FRONTEND_PORT}:${FRONTEND_PORT}"
        env_file:
            - .env.prod
        depends_on:
            - db

    ws:
        build:
            context: ./websocket-server
            dockerfile: ./docker/Dockerfile.prod
        restart: unless-stopped
        container_name: "websocket-server"
        ports:
            - "${WS_PORT}:${WS_PORT}"
        env_file:
            - .env.prod
        depends_on:
            - db

volumes:
    mysql_data:
